wd<-("~/PATH")
setwd(wd)

set.seed(223)

library("dplyr")
library("ggplot2")
library("GeoThinneR")
library("tidyterra")
library("rnaturalearth")
library("rnaturalearthdata")
library("ggpattern")
library("ggnewscale")
library("ggpattern")
library("geosphere")
library("terra")
library("smoothr")
library("devtools")
devtools::install_github("ropensci/rnaturalearthhires")
